"use client";
import {useEffect,useState} from "react";
type Profile={name:string;age:number;avatar:string;stars:number;coins:number;xp:number;streak:number;correct:number;wrong:number;worlds:number[]};
type Screen="home"|"profile"|"intro"|"map"|"lesson"|"achievements"|"parents"|"settings";
const worlds=[["👋","Hello!","Greetings"],["🎨","Colors","Cores"],["🔢","Numbers","Números"],["🐆","Animals","Animais"],["🍎","Food","Comidas"],["👨‍👩‍👧","Family","Família"],["🏫","School","Escola"],["👕","Clothes","Roupas"],["🏃","Actions","Ações"],["💬","Let's Talk!","Conversação"]];
const questions=[
 {type:"🔊 Listen and Choose",prompt:"Listen and choose the greeting!",speak:"Hello",options:[["👋","Hello"],["🌙","Good night"],["👋🏼","Goodbye"]],answer:"Hello",tip:"It starts with the sound ‘he’."},
 {type:"🖼️ Look and Choose",prompt:"Geovana is saying goodbye. Choose the word!",visual:"👋",options:[["☀️","Good morning"],["👋","Goodbye"],["😊","My name is"]],answer:"Goodbye",tip:"We say it when we leave."},
 {type:"🧩 Build the Sentence",prompt:"Complete Geovana's introduction:",visual:"👧🏽",options:[["💬","My name is Geovana."],["💬","Good afternoon cat."],["💬","Goodbye name."]],answer:"My name is Geovana.",tip:"Use ‘My name is...’ to introduce yourself."},
 {type:"❓ What do you say?",prompt:"It is morning. What do you say?",visual:"🌅",options:[["🌞","Good morning"],["🌤️","Good afternoon"],["🌙","Good night"]],answer:"Good morning",tip:"Morning is before midday."},
 {type:"🎯 Mission Challenge",prompt:"Find the friendly greeting!",visual:"🦜",options:[["👋","Hi"],["🍌","Banana"],["🔵","Blue"]],answer:"Hi",tip:"A short greeting with two letters."}
];
const fresh:Profile={name:"",age:8,avatar:"🧒🏽",stars:0,coins:0,xp:0,streak:0,correct:0,wrong:0,worlds:[]};
export default function Home(){
 const[screen,setScreen]=useState<Screen>("home"),[profile,setProfile]=useState<Profile>(fresh),[loaded,setLoaded]=useState(false),[q,setQ]=useState(0),[feedback,setFeedback]=useState(""),[tries,setTries]=useState(0),[parentPass,setParentPass]=useState(""),[unlocked,setUnlocked]=useState(false),[sound,setSound]=useState(true);
 useEffect(()=>{const p=localStorage.getItem("geovana-profile");if(p)setProfile(JSON.parse(p));setLoaded(true)},[]);useEffect(()=>{if(loaded)localStorage.setItem("geovana-profile",JSON.stringify(profile))},[profile,loaded]);
 const level=Math.floor(profile.xp/100)+1,accuracy=(profile.correct+profile.wrong)?Math.round(profile.correct/(profile.correct+profile.wrong)*100):0;
 const speak=(text:string)=>{if(!sound)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.78;speechSynthesis.speak(u)};
 const saveProfile=(e:React.FormEvent)=>{e.preventDefault();setScreen("intro");setTimeout(()=>speak("Hello! I'm Geovana! Welcome to Geovana's Adventures!"),350)};
 const answer=(value:string)=>{if(feedback)return;const ok=value===questions[q].answer;if(ok){setFeedback(["Great job!","Excellent!","Amazing!","You got it!"][q%4]);setProfile(p=>({...p,correct:p.correct+1,streak:p.streak+1,stars:p.stars+1,coins:p.coins+5,xp:p.xp+20}));speak("Great job!")}else{const n=tries+1;setTries(n);setFeedback(n>=2?`💡 ${questions[q].tip}`:"Almost! Try again!");setProfile(p=>({...p,wrong:p.wrong+1,streak:0}));speak("Good try! Let's try one more time!");setTimeout(()=>setFeedback(""),n>=2?2600:1400)}};
 const next=()=>{if(q<questions.length-1){setQ(q+1);setFeedback("");setTries(0)}else{setProfile(p=>({...p,worlds:Array.from(new Set([...p.worlds,1])),stars:p.stars+3,coins:p.coins+20,xp:p.xp+40}));setQ(0);setFeedback("");setScreen("map")}};
 const top=<header className="top"><button className="brand" onClick={()=>setScreen("home")}><span>🌟</span><b>GEOVANA'S<br/><small>ADVENTURES</small></b></button><div className="stats"><span>🏅 {level}</span><span>⭐ {profile.stars}</span><span>🪙 {profile.coins}</span><span>🔥 {profile.streak}</span><button className="round" onClick={()=>setSound(!sound)}>{sound?"🔊":"🔇"}</button></div></header>;
 if(!loaded)return <main className="loading">🌟 Loading adventure...</main>;
 return <main>{top}
 {screen==="home"&&<section className="hero"><div className="heroCopy"><p className="eyebrow">A magical English journey</p><h1>AS AVENTURAS<br/><em>DE GEOVANA</em></h1><h2>GEOVANA'S ADVENTURES</h2><p>Aprenda inglês enquanto vive grandes aventuras!<br/><b>Learn English While Having Great Adventures!</b></p><div className="homeBtns"><button className="primary" onClick={()=>setScreen(profile.name?"map":"profile")}>▶ {profile.name?"CONTINUAR — CONTINUE":"JOGAR — PLAY"}</button><button onClick={()=>setScreen("map")}>🗺️ MAPA — ADVENTURE MAP</button><button onClick={()=>setScreen("achievements")}>🏆 CONQUISTAS — ACHIEVEMENTS</button><button onClick={()=>setScreen("settings")}>⚙️ CONFIGURAÇÕES — SETTINGS</button></div></div><div className="mascot"><div className="speech">Hello, explorer! 👋<br/><small>Vamos aprender inglês?</small></div><img src="/geovana.png" alt="Geovana sorrindo"/><span className="leaf">🌿</span></div></section>}
 {screen==="profile"&&<section className="panel profile"><div className="miniMascot"><img src="/geovana.png" alt="Geovana"/></div><form onSubmit={saveProfile}><p className="eyebrow">YOUR EXPLORER PROFILE</p><h2>What's your name?</h2><label>Qual é o seu nome?<input autoFocus required maxLength={20} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="Digite seu nome"/></label><h2>How old are you?</h2><label>Quantos anos você tem?<input type="range" min="7" max="12" value={profile.age} onChange={e=>setProfile({...profile,age:+e.target.value})}/><strong className="age">{profile.age} anos</strong></label><h2>Choose your avatar</h2><div className="avatars">{["🧒🏽","👧🏽","🧑🏼","👦🏾","👧🏻","🧑🏿"].map(a=><button type="button" className={profile.avatar===a?"selected":""} onClick={()=>setProfile({...profile,avatar:a})} key={a}>{a}</button>)}</div><button className="primary">🚀 START MY ADVENTURE!</button></form></section>}
 {screen==="intro"&&<section className="intro"><div className="introScene"><img src="/geovana.png" alt="Geovana"/><div className="dialog"><span>👋</span><h2>Hello! I'm Geovana!</h2><p>Welcome to Geovana's Adventures!</p><b>Are you ready to learn English and have fun?</b><button className="listen" onClick={()=>speak("Hello! I'm Geovana! Welcome to Geovana's Adventures! Are you ready to learn English and have fun?")}>🔊 Listen again</button><button className="primary" onClick={()=>setScreen("map")}>🚀 YES! LET'S GO!</button></div></div></section>}
 {screen==="map"&&<section className="mapPage"><div className="sectionHead"><div><p className="eyebrow">THE AMAZON ADVENTURE MAP</p><h2>Choose your next adventure!</h2><p>Escolha sua próxima aventura, {profile.name||"explorer"}!</p></div><div className="progress"><b>{profile.worlds.length}/10 mundos</b><span><i style={{width:`${profile.worlds.length*10}%`}}/></span></div></div><div className="mapGrid">{worlds.map((w,i)=>{const open=i===0||profile.worlds.includes(i);return <button key={w[1]} disabled={!open} className={`world ${profile.worlds.includes(i+1)?"done":""}`} onClick={()=>{if(i===0){setQ(0);setFeedback("");setScreen("lesson")}}}><span className="worldNo">{profile.worlds.includes(i+1)?"✓":i+1}</span><i>{open?w[0]:"🔒"}</i><b>{w[1]}</b><small>{w[2]}</small><em>{i===0?"PLAY NOW":open?"OPEN":"Complete previous world"}</em></button>})}</div></section>}
 {screen==="lesson"&&<section className="lesson"><div className="lessonTop"><button onClick={()=>setScreen("map")}>← Map</button><div><b>WORLD 1 · HELLO!</b><span>{questions.map((_,i)=><i key={i} className={i<=q?"on":""}/>)}</span></div><span>❤️ ❤️ ❤️</span></div><div className="questCard"><div className="guide"><img src="/geovana.png" alt="Geovana guia"/><div><small>{questions[q].type}</small><h2>{questions[q].prompt}</h2></div></div>{questions[q].visual&&<div className="visual">{questions[q].visual}</div>}<button className="listen big" onClick={()=>speak(questions[q].answer)}>🔊 LISTEN</button><div className="options">{questions[q].options.map(([icon,label])=><button key={label} onClick={()=>answer(label)}><span>{icon}</span><b>{label}</b><small>Tap to choose</small></button>)}</div>{feedback&&<div className={`feedback ${feedback.includes("Try")||feedback.includes("💡")?"try":"good"}`}><b>{feedback}</b>{!feedback.includes("Try")&&!feedback.includes("💡")&&<button onClick={next}>{q===questions.length-1?"🏆 FINISH WORLD":"NEXT →"}</button>}</div>}</div></section>}
 {screen==="achievements"&&<section className="panel"><div className="sectionHead"><div><p className="eyebrow">MY TREASURE ROOM</p><h2>Conquistas — Achievements</h2></div></div><div className="badges">{[["🌟","First Star",profile.stars>0],["🔥","Hot Streak",profile.streak>=3],["👋","Hello Hero",profile.worlds.includes(1)],["💯","Word Master",profile.correct>=10],["🪙","Treasure Hunter",profile.coins>=50],["🏆","World Explorer",profile.worlds.length>=5]].map(([a,b,on])=><article className={on?"earned":""} key={String(b)}><i>{a}</i><b>{b}</b><small>{on?"Unlocked!":"Keep exploring"}</small></article>)}</div><button onClick={()=>setScreen("home")}>← Voltar</button></section>}
 {screen==="settings"&&<section className="panel settings"><p className="eyebrow">SETTINGS</p><h2>Configurações</h2><button onClick={()=>setSound(!sound)}>🔊 Áudio em inglês <b>{sound?"LIGADO":"DESLIGADO"}</b></button><button onClick={()=>setScreen("profile")}>👤 Editar perfil</button><button onClick={()=>setScreen("parents")}>🔐 Área dos pais/professor</button><button onClick={()=>setScreen("home")}>← Voltar ao início</button></section>}
 {screen==="parents"&&<section className="panel parents">{!unlocked?<div className="lock"><i>🔐</i><h2>Área dos pais/professor</h2><p>Digite a senha padrão <b>1234</b> nesta versão demonstrativa.</p><input type="password" value={parentPass} onChange={e=>setParentPass(e.target.value)} placeholder="Senha"/><button className="primary" onClick={()=>setUnlocked(parentPass==="1234")}>ENTRAR</button><button onClick={()=>setScreen("settings")}>Cancelar</button></div>:<><div className="sectionHead"><div><p className="eyebrow">LEARNING REPORT</p><h2>Progresso de {profile.name}</h2><p>{profile.age} anos · Nível {level}</p></div><button onClick={()=>setScreen("settings")}>Sair</button></div><div className="report">{[["⭐",profile.stars,"Estrelas"],["✅",profile.correct,"Acertos"],["📊",`${accuracy}%`,"Precisão"],["🌍",profile.worlds.length,"Mundos"]].map(x=><article key={String(x[2])}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><h3>Desempenho por tema</h3><div className="bar"><label>Hello! <b>{accuracy}%</b></label><span><i style={{width:`${accuracy}%`}}/></span></div><div className="teacherNote">💡 <b>Recomendação:</b> repita palavras com áudio e comemore cada pequena conquista. O progresso é salvo automaticamente neste aparelho.</div></>}</section>}
 </main>}
